[package]
name = "lambda_pdf_rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.105"
taffy = "0.9.2"
tl = "0.7.8"

[dependencies.skia-safe]
version = "0.91.0"
default-features = false
features = ["textlayout", "pdf", "binary-cache"]
